Feature/select g house
FACN1/PAS-MVP pull request #34
Opened 2017-06-04 14:32 UTC by philawsophizing

2017-06-04 19:57 UTC, Karyum approved these changes

2017-06-05 07:24 UTC, jbesraa requested changes

2017-06-05 07:24 UTC, esraajb commented on src/components/search_list.jsx
> +          <button
maybe this button should be a different component and then the bind function wont be inside the map function

2017-06-05 07:24 UTC, esraajb commented on src/containers/select_guesthouse.jsx
> +        return curr;
curr and current?

2017-06-06 08:32 UTC, philawsophizing commented
@esraajb more like this? :maple_leaf:

2017-06-06 09:02 UTC, jbesraa requested changes
looks good 👍, left a couple of comments. Also, no issue referred

2017-06-06 09:02 UTC, esraajb commented on src/containers/select_guesthouse.jsx
> +      tagLine: 'Park & Sleep',
are title and tagLine ever change? if not, then its pointless to put them in a state.

2017-06-06 09:02 UTC, esraajb commented on src/containers/select_guesthouse.jsx
> +      db: [],
maybe instead of db, use 'guestHousesList'? might be clearer for the reader

2017-06-06 09:03 UTC, philawsophizing commented on src/containers/select_guesthouse.jsx
> +      tagLine: 'Park & Sleep',
They are going to be changed (header will update based on these values). Next PR.

2017-06-06 09:03 UTC, philawsophizing commented on src/containers/select_guesthouse.jsx
> +      db: [],
Good shout

2017-06-06 09:11 UTC, philawsophizing commented
@esraajb ref#22 was in the commit message :smile: should it be in the comment as well?

Changes made.

2017-06-06 09:33 UTC, esraajb commented
Yea, should be in the description

2017-06-06 09:44 UTC, philawsophizing commented
@esraajb Cool cool, done. And will do going forward. Good to merge?

2017-06-06 10:07 UTC, merged